version: "3.2"

services:
  node_backend :
    container_name : eduapp
    image : edu-app
    build :
     context: . 
    volumes:
      - .:/app
    command: npm run start:dev    
    ports:
     - "5000:5000" 

    environment: 
     - External_port=5000
     - POSTGRES_USER=OMAR
     - POSTGRES_PASSWORD=123456
     - POSTGRES_DB=eduapp
     - POSTGRES_HOST=node_db

    depends_on: 
    - node_db


  # frontend:
  #     build: ./ReactDashboard
  #         # context: ./ReactDashboard
  #         # dockerfile: Dockerfile
  #     command: npm start
  #     container_name: frontend
  #     ports:
  #       - "3000:3000"        
  #     volumes: 
  #       - ./:/frontend
  #       - /frontend/node_modules


  node_db:
    container_name : node_db
    image: "postgres"
    ports: 
     - "5432:5432"
    
    volumes: 
      - db:/var/lib/postgresql/data

    environment: 
     - POSTGRES_USER=OMAR
     - POSTGRES_PASSWORD=123456
     - POSTGRES_DB=eduapp
     
volumes:
  db: {}